dateFormat: 2006.01.02
author: Miguel Simoni
showSubheader: false

copyright:
  sinceYear: 2020
  owner: Miguel Simoni

languagesMenuEnabled: true

breadcrumb:
  showCurrent: false
  divider: ''

pagination:
  loader: true

# Bootstrap Themes
theme:
  # static: default # available themes in data/themes.yml
  selector: true

# OpenGraph
title: "My cool site"
description: "Text about my cool site"
images: ["site-feature-image.jpg"]

# ShareThis
# sharethisProperty: sharethis-property

# Social Networks
social:
  - network: twitter
    link: "#"
    icon: "fab fa-twitter-square fa-3x"
  - network: facebook
    link: "#"
    icon: "fab fa-facebook-square fa-3x"
  - network: instagram
    link: "#"
    icon: "fab fa-instagram-square fa-3x"
  - network: github
    link: "#"
    icon: "fab fa-github-square fa-3x"
  - network: medium
    link: "#"
    icon: "fab fa-medium fa-3x"
  - network: linkedin
    link: "#"
    icon: "fab fa-linkedin fa-3x"
  - network: twitch
    link: "#"
    icon: "fab fa-twitch fa-3x"
  - network: youtube
    link: "#"
    icon: "fab fa-youtube-square fa-3x"
  - network: reddit
    link: "#"
    icon: "fab fa-reddit-square fa-3x"
  - network: whatsapp
    link: "#"
    icon: "fab fa-whatsapp-square fa-3x"

# Forms
form:
  validation:
    namePattern: ^[a-zA-Z]{3,}[a-zA-Z\s\-]*$
    emailPattern: ^[a-zA-Z0-9_\-\.]+@[a-zA-Z0-9_\-]+\.[a-zA-Z]{2,4}(\.[a-zA-Z]{2})?$
    telephonePattern: ^[\+\(\)\-\d]+$
  recaptcha:
    v2:
      siteKey: 6LcwgoMiAAAAAAODQdhmoRl-FdlnoWvj47LZSp8I
  contact:
    action: https://formspree.io/f/maykbglg

background:
  image: "../images/background-astro.png"
  parallax: true
  speed: 10
