dateFormat: 2006.01.02
author: Miguel Simoni
showSubheader: false

copyright:
  sinceYear: 2020
  owner: Miguel Simoni

languagesMenuEnabled: true

breadcrumb:
  showCurrent: false
  divider: ''

pagination:
  loader: true

# Bootswatch Themes
bootswatch:
  enabled: false
  theme: spacelab
# default   cerulean  cosmo     cyborg    darkly      flatly      journal   litera 
# lumen     lux       materia   minty     morph       pulse       quartz    sandstone 
# simplex   sketchy   slate     solar     spacelab    superhero   united    vapor
# yeti      zephyr

# OpenGraph
title: "My cool site"
description: "Text about my cool site"
images: ["site-feature-image.jpg"]

# Google Analytics
googleAnalytics: "UA-123-45"

# Disqus
disqusShortname: "yourdiscussshortname"

contact:
  formAction: http://localhost:1313/
  validation:
    namePattern: ^[a-zA-Z]{3,}[a-zA-Z\s\-]*$
    emailPattern: ^[a-zA-Z0-9_\-\.]+@[a-zA-Z0-9_\-]+\.[a-zA-Z]{2,4}(\.[a-zA-Z]{2})?$

background:
  image: "../images/background-astro.png"
  parallax: true
  speed: 10
