dateFormat: 2006.01.02
author: Miguel Simoni
showSubheader: true

copyright:
  sinceYear: 2020
  owner: Miguel Simoni

languagesMenuEnabled: true

breadcrumb:
  showCurrent: true
  divider: ''

pagination:
  loader: true

# Bootswatch Themes
bootswatch:
  enabled: false
  theme: spacelab
# default   cerulean  cosmo     cyborg    darkly      flatly      journal   litera 
# lumen     lux       materia   minty     morph       pulse       quartz    sandstone 
# simplex   sketchy   slate     solar     spacelab    superhero   united    vapor
# yeti      zephyr

# OpenGraph
title: "My cool site"
description: "Text about my cool site"
images: ["site-feature-image.jpg"]

# Google Analytics
googleAnalytics: "UA-123-45"

# Disqus
disqusShortname: "yourdiscussshortname"
